// Generated by lsc from frame_core.ts

function framePreserved(pre: (int) -> int, post: (int) -> int, inFrame: (int) -> bool, files: seq<int>): bool
  decreases |files|
{
  ((|files| == 0) || (var f := files[0]; (var ok := (inFrame(f) || (pre(f) == post(f))); (ok && framePreserved(pre, post, inFrame, files[1..])))))
}

function nonVacuous(inFrame: (int) -> bool, files: seq<int>): bool
  decreases |files|
{
  if (|files| == 0) then
    false
  else
    (!(inFrame(files[0])) || nonVacuous(inFrame, files[1..]))
}

function vacuousProtectsNothing(pre: (int) -> int, post: (int) -> int, inFrame: (int) -> bool, files: seq<int>): bool
  requires forall i: int :: ((0 <= i) ==> (i < |files|) ==> inFrame(files[i]))
{
  true
}

lemma vacuousProtectsNothing_ensures(pre: (int) -> int, post: (int) -> int, inFrame: (int) -> bool, files: seq<int>)
  requires forall i: int :: ((0 <= i) ==> (i < |files|) ==> inFrame(files[i]))
  ensures framePreserved(pre, post, inFrame, files)
  decreases |files|
{
  if |files| == 0 {
  } else {
    vacuousProtectsNothing_ensures(pre, post, inFrame, files[1..]);
  }
}

function outOfFrameChangeCaught(pre: (int) -> int, post: (int) -> int, inFrame: (int) -> bool, files: seq<int>, k: int): bool
  requires (0 <= k)
  requires (k < |files|)
  requires !(inFrame(files[k]))
  requires (pre(files[k]) != post(files[k]))
{
  true
}

lemma outOfFrameChangeCaught_ensures(pre: (int) -> int, post: (int) -> int, inFrame: (int) -> bool, files: seq<int>, k: int)
  requires (0 <= k)
  requires (k < |files|)
  requires !(inFrame(files[k]))
  requires (pre(files[k]) != post(files[k]))
  ensures !(framePreserved(pre, post, inFrame, files))
  decreases |files|
{
  if k == 0 {
  } else {
    outOfFrameChangeCaught_ensures(pre, post, inFrame, files[1..], k - 1);
  }
}

function frameDominance(pre: (int) -> int, post: (int) -> int, star: (int) -> bool, scoped: (int) -> bool, files: seq<int>, k: int): bool
  requires forall f: int :: star(f)
  requires (0 <= k)
  requires (k < |files|)
  requires !(scoped(files[k]))
  requires (pre(files[k]) != post(files[k]))
{
  true
}

lemma frameDominance_ensures(pre: (int) -> int, post: (int) -> int, star: (int) -> bool, scoped: (int) -> bool, files: seq<int>, k: int)
  requires forall f: int :: star(f)
  requires (0 <= k)
  requires (k < |files|)
  requires !(scoped(files[k]))
  requires (pre(files[k]) != post(files[k]))
  ensures framePreserved(pre, post, star, files)
  ensures !(framePreserved(pre, post, scoped, files))
{
  vacuousProtectsNothing_ensures(pre, post, star, files);
  outOfFrameChangeCaught_ensures(pre, post, scoped, files, k);
}
