// Generated by lsc from loop_core.ts

function bodyTaint(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, body: seq<int>): bool
  decreases |body|
{
  if (|body| == 0) then
    t0
  else
    var next := (if sanitizes(body[0]) then false else (t0 || introduces(body[0])));
    bodyTaint(introduces, sanitizes, next, body[1..])
}

function leaksBody(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, t0: bool, body: seq<int>): bool
  decreases |body|
{
  if (|body| == 0) then
    false
  else
    var here := (isSink(body[0]) && t0);
    var next := (if sanitizes(body[0]) then false else (t0 || introduces(body[0])));
    (here || leaksBody(introduces, sanitizes, isSink, next, body[1..]))
}

function iterTaint(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, body: seq<int>, n: nat): bool
  decreases n
{
  if (n == 0) then
    t0
  else
    bodyTaint(introduces, sanitizes, iterTaint(introduces, sanitizes, t0, body, (n - 1)), body)
}

function leaksUpTo(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, t0: bool, body: seq<int>, n: nat): bool
  decreases n
{
  if (n == 0) then
    false
  else
    (leaksBody(introduces, sanitizes, isSink, iterTaint(introduces, sanitizes, t0, body, (n - 1)), body) || leaksUpTo(introduces, sanitizes, isSink, t0, body, (n - 1)))
}

function bodyMonotone(introduces: (int) -> bool, sanitizes: (int) -> bool, t0a: bool, t0b: bool, body: seq<int>): bool
  requires (t0a ==> t0b)
{
  true
}

lemma bodyMonotone_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, t0a: bool, t0b: bool, body: seq<int>)
  requires (t0a ==> t0b)
  ensures (bodyTaint(introduces, sanitizes, t0a, body) ==> bodyTaint(introduces, sanitizes, t0b, body))
  decreases |body|
{
  if |body| == 0 {
  } else {
    bodyMonotone_ensures(introduces, sanitizes,
      (if sanitizes(body[0]) then false else (t0a || introduces(body[0]))),
      (if sanitizes(body[0]) then false else (t0b || introduces(body[0]))),
      body[1..]);
  }
}

function leaksBodyMonotone(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, t0a: bool, t0b: bool, body: seq<int>): bool
  requires (t0a ==> t0b)
{
  true
}

lemma leaksBodyMonotone_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, t0a: bool, t0b: bool, body: seq<int>)
  requires (t0a ==> t0b)
  ensures (leaksBody(introduces, sanitizes, isSink, t0a, body) ==> leaksBody(introduces, sanitizes, isSink, t0b, body))
  decreases |body|
{
  if |body| == 0 {
  } else {
    leaksBodyMonotone_ensures(introduces, sanitizes, isSink,
      (if sanitizes(body[0]) then false else (t0a || introduces(body[0]))),
      (if sanitizes(body[0]) then false else (t0b || introduces(body[0]))),
      body[1..]);
  }
}

function satPrefixpoint(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, body: seq<int>): bool
{
  true
}

lemma satPrefixpoint_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, body: seq<int>)
  ensures (bodyTaint(introduces, sanitizes, (t0 || bodyTaint(introduces, sanitizes, t0, body)), body) ==> (t0 || bodyTaint(introduces, sanitizes, t0, body)))
{
  if !(t0 || bodyTaint(introduces, sanitizes, t0, body)) {
    // sat is false, so t0 is false and sat == t0; hence bodyTaint(sat) == bodyTaint(t0), which is false.
    assert (t0 || bodyTaint(introduces, sanitizes, t0, body)) == t0;
    assert bodyTaint(introduces, sanitizes, (t0 || bodyTaint(introduces, sanitizes, t0, body)), body) == bodyTaint(introduces, sanitizes, t0, body);
  }
}

function loopExitSound(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, body: seq<int>, n: nat): bool
{
  true
}

lemma loopExitSound_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, body: seq<int>, n: nat)
  ensures (iterTaint(introduces, sanitizes, t0, body, n) ==> (t0 || bodyTaint(introduces, sanitizes, t0, body)))
  decreases n
{
  if n == 0 {
  } else {
    loopExitSound_ensures(introduces, sanitizes, t0, body, n - 1);
    bodyMonotone_ensures(introduces, sanitizes,
      iterTaint(introduces, sanitizes, t0, body, n - 1),
      (t0 || bodyTaint(introduces, sanitizes, t0, body)),
      body);
    satPrefixpoint_ensures(introduces, sanitizes, t0, body);
  }
}

function loopLeakSound(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, t0: bool, body: seq<int>, n: nat): bool
{
  true
}

lemma loopLeakSound_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, t0: bool, body: seq<int>, n: nat)
  ensures (leaksUpTo(introduces, sanitizes, isSink, t0, body, n) ==> leaksBody(introduces, sanitizes, isSink, (t0 || bodyTaint(introduces, sanitizes, t0, body)), body))
  decreases n
{
  if n == 0 {
  } else {
    loopLeakSound_ensures(introduces, sanitizes, isSink, t0, body, n - 1);
    loopExitSound_ensures(introduces, sanitizes, t0, body, n - 1);
    leaksBodyMonotone_ensures(introduces, sanitizes, isSink,
      iterTaint(introduces, sanitizes, t0, body, n - 1),
      (t0 || bodyTaint(introduces, sanitizes, t0, body)),
      body);
  }
}
