// Generated by lsc from prov_core.ts

function provAfter(introduces: (int, int) -> bool, sanitizes: (int, int) -> bool, t0: bool, tools: seq<int>, lbl: int): bool
  decreases |tools|
{
  if (|tools| == 0) then
    t0
  else
    var next := (if sanitizes(tools[0], lbl) then false else (t0 || introduces(tools[0], lbl)));
    provAfter(introduces, sanitizes, next, tools[1..], lbl)
}

function provKeeps(introduces: (int, int) -> bool, sanitizes: (int, int) -> bool, t0: bool, tools: seq<int>, lbl: int): bool
  requires t0
  requires forall i: int :: ((0 <= i) ==> (i < |tools|) ==> !(sanitizes(tools[i], lbl)))
  decreases |tools|
{
  ((|tools| == 0) || (var next := (if sanitizes(tools[0], lbl) then false else (t0 || introduces(tools[0], lbl))); provKeeps(introduces, sanitizes, next, tools[1..], lbl)))
}

lemma provKeeps_ensures(introduces: (int, int) -> bool, sanitizes: (int, int) -> bool, t0: bool, tools: seq<int>, lbl: int)
  requires t0
  requires forall i: int :: ((0 <= i) ==> (i < |tools|) ==> !(sanitizes(tools[i], lbl)))
  ensures (provAfter(introduces, sanitizes, t0, tools, lbl) == true)
{
}

function endSanitizerClearsLabel(introduces: (int, int) -> bool, sanitizes: (int, int) -> bool, t0: bool, tools: seq<int>, lbl: int): bool
  requires (|tools| > 0)
  requires sanitizes(tools[(|tools| - 1)], lbl)
  decreases |tools|
{
  ((|tools| == 1) || (var next := (if sanitizes(tools[0], lbl) then false else (t0 || introduces(tools[0], lbl))); endSanitizerClearsLabel(introduces, sanitizes, next, tools[1..], lbl)))
}

lemma endSanitizerClearsLabel_ensures(introduces: (int, int) -> bool, sanitizes: (int, int) -> bool, t0: bool, tools: seq<int>, lbl: int)
  requires (|tools| > 0)
  requires sanitizes(tools[(|tools| - 1)], lbl)
  ensures (provAfter(introduces, sanitizes, t0, tools, lbl) == false)
  decreases |tools|
{
  if |tools| == 1 {
    assert sanitizes(tools[0], lbl);
  } else {
    var next := (if sanitizes(tools[0], lbl) then false else (t0 || introduces(tools[0], lbl)));
    assert tools[1..][|tools[1..]| - 1] == tools[|tools| - 1];
    endSanitizerClearsLabel_ensures(introduces, sanitizes, next, tools[1..], lbl);
  }
}

function introducedSourcePresent(introduces: (int, int) -> bool, sanitizes: (int, int) -> bool, tools: seq<int>, lbl: int): bool
  requires forall i: int :: ((0 <= i) ==> (i < |tools|) ==> !(sanitizes(tools[i], lbl)))
  requires exists i: int :: (((0 <= i) && (i < |tools|)) && introduces(tools[i], lbl))
{
  true
}

lemma introducedSourcePresent_ensures(introduces: (int, int) -> bool, sanitizes: (int, int) -> bool, tools: seq<int>, lbl: int)
  requires forall i: int :: ((0 <= i) ==> (i < |tools|) ==> !(sanitizes(tools[i], lbl)))
  requires exists i: int :: (((0 <= i) && (i < |tools|)) && introduces(tools[i], lbl))
  ensures (provAfter(introduces, sanitizes, false, tools, lbl) == true)
  decreases |tools|
{
  assert |tools| > 0;
  if introduces(tools[0], lbl) {
    assert !sanitizes(tools[0], lbl);
    provKeeps_ensures(introduces, sanitizes, true, tools[1..], lbl);
  } else {
    var k :| (0 <= k && k < |tools|) && introduces(tools[k], lbl);
    assert k != 0;
    assert tools[1..][k - 1] == tools[k];
    introducedSourcePresent_ensures(introduces, sanitizes, tools[1..], lbl);
  }
}

function joinFlagsContributingSource(introduces: (int, int) -> bool, sanitizes: (int, int) -> bool, branchA: seq<int>, branchB: seq<int>, lbl: int): bool
  requires forall i: int :: ((0 <= i) ==> (i < |branchA|) ==> !(sanitizes(branchA[i], lbl)))
  requires exists i: int :: (((0 <= i) && (i < |branchA|)) && introduces(branchA[i], lbl))
{
  true
}

lemma joinFlagsContributingSource_ensures(introduces: (int, int) -> bool, sanitizes: (int, int) -> bool, branchA: seq<int>, branchB: seq<int>, lbl: int)
  requires forall i: int :: ((0 <= i) ==> (i < |branchA|) ==> !(sanitizes(branchA[i], lbl)))
  requires exists i: int :: (((0 <= i) && (i < |branchA|)) && introduces(branchA[i], lbl))
  ensures (provAfter(introduces, sanitizes, false, branchA, lbl) || provAfter(introduces, sanitizes, false, branchB, lbl))
{
  introducedSourcePresent_ensures(introduces, sanitizes, branchA, lbl);
}
