// Generated by lsc from taint_core.ts

function taintAfter(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, tools: seq<int>): bool
  decreases |tools|
{
  if (|tools| == 0) then
    t0
  else
    var next := (if sanitizes(tools[0]) then false else (t0 || introduces(tools[0])));
    taintAfter(introduces, sanitizes, next, tools[1..])
}

function taintMonotone(introduces: (int) -> bool, sanitizes: (int) -> bool, t0a: bool, t0b: bool, tools: seq<int>): bool
  requires (t0a ==> t0b)
  decreases |tools|
{
  ((|tools| == 0) || (var na := (if sanitizes(tools[0]) then false else (t0a || introduces(tools[0]))); (var nb := (if sanitizes(tools[0]) then false else (t0b || introduces(tools[0]))); taintMonotone(introduces, sanitizes, na, nb, tools[1..]))))
}

lemma taintMonotone_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, t0a: bool, t0b: bool, tools: seq<int>)
  requires (t0a ==> t0b)
  ensures (taintAfter(introduces, sanitizes, t0a, tools) ==> taintAfter(introduces, sanitizes, t0b, tools))
  decreases |tools|
{
  if |tools| == 0 {
  } else {
    var na := (if sanitizes(tools[0]) then false else (t0a || introduces(tools[0])));
    var nb := (if sanitizes(tools[0]) then false else (t0b || introduces(tools[0])));
    taintMonotone_ensures(introduces, sanitizes, na, nb, tools[1..]);
  }
}

function noSanitizerKeepsTaint(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, tools: seq<int>): bool
  requires t0
  requires forall i: int :: ((0 <= i) ==> (i < |tools|) ==> !(sanitizes(tools[i])))
  decreases |tools|
{
  ((|tools| == 0) || (var next := (if sanitizes(tools[0]) then false else (t0 || introduces(tools[0]))); noSanitizerKeepsTaint(introduces, sanitizes, next, tools[1..])))
}

lemma noSanitizerKeepsTaint_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, tools: seq<int>)
  requires t0
  requires forall i: int :: ((0 <= i) ==> (i < |tools|) ==> !(sanitizes(tools[i])))
  ensures (taintAfter(introduces, sanitizes, t0, tools) == true)
{
}

function endSanitizerClean(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, tools: seq<int>): bool
  requires (|tools| > 0)
  requires sanitizes(tools[(|tools| - 1)])
  decreases |tools|
{
  ((|tools| == 1) || (var next := (if sanitizes(tools[0]) then false else (t0 || introduces(tools[0]))); endSanitizerClean(introduces, sanitizes, next, tools[1..])))
}

lemma endSanitizerClean_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, tools: seq<int>)
  requires (|tools| > 0)
  requires sanitizes(tools[(|tools| - 1)])
  ensures (taintAfter(introduces, sanitizes, t0, tools) == false)
  decreases |tools|
{
  if |tools| == 1 {
    assert sanitizes(tools[0]);
  } else {
    var next := (if sanitizes(tools[0]) then false else (t0 || introduces(tools[0])));
    assert tools[1..][|tools[1..]| - 1] == tools[|tools| - 1];
    endSanitizerClean_ensures(introduces, sanitizes, next, tools[1..]);
  }
}
