// Generated by lsc from wf_core.ts

datatype Wf = done | tool(tool: int, rest: Wf) | cond(thenB: Wf, elseB: Wf, rest: Wf)

function taintWf(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, wf: Wf): bool
  decreases wf
{
  match wf {
    case done =>
      t0
    case tool(i_wf_tool, i_wf_rest) =>
      var next := (if sanitizes(i_wf_tool) then false else (t0 || introduces(i_wf_tool)));
      taintWf(introduces, sanitizes, next, i_wf_rest)
    case cond(i_wf_thenB, i_wf_elseB, i_wf_rest) =>
      var branched := (taintWf(introduces, sanitizes, t0, i_wf_thenB) || taintWf(introduces, sanitizes, t0, i_wf_elseB));
      taintWf(introduces, sanitizes, branched, i_wf_rest)
  }
}

function taintWfConcrete(introduces: (int) -> bool, sanitizes: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf): bool
  decreases wf
{
  match wf {
    case done =>
      t0
    case tool(i_wf_tool, i_wf_rest) =>
      var next := (if sanitizes(i_wf_tool) then false else (t0 || introduces(i_wf_tool)));
      taintWfConcrete(introduces, sanitizes, chooseThen, next, i_wf_rest)
    case cond(i_wf_thenB, i_wf_elseB, i_wf_rest) =>
      var branched := (if chooseThen(wf) then taintWfConcrete(introduces, sanitizes, chooseThen, t0, i_wf_thenB) else taintWfConcrete(introduces, sanitizes, chooseThen, t0, i_wf_elseB));
      taintWfConcrete(introduces, sanitizes, chooseThen, branched, i_wf_rest)
  }
}

function taintWfMonotone(introduces: (int) -> bool, sanitizes: (int) -> bool, t0a: bool, t0b: bool, wf: Wf): bool
  requires (t0a ==> t0b)
{
  true
}

lemma taintWfMonotone_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, t0a: bool, t0b: bool, wf: Wf)
  requires (t0a ==> t0b)
  ensures (taintWf(introduces, sanitizes, t0a, wf) ==> taintWf(introduces, sanitizes, t0b, wf))
  decreases wf
{
  match wf {
    case done =>
    case tool(t, rest) =>
      taintWfMonotone_ensures(introduces, sanitizes,
        (if sanitizes(t) then false else (t0a || introduces(t))),
        (if sanitizes(t) then false else (t0b || introduces(t))),
        rest);
    case cond(thenB, elseB, rest) =>
      taintWfMonotone_ensures(introduces, sanitizes, t0a, t0b, thenB);
      taintWfMonotone_ensures(introduces, sanitizes, t0a, t0b, elseB);
      taintWfMonotone_ensures(introduces, sanitizes,
        (taintWf(introduces, sanitizes, t0a, thenB) || taintWf(introduces, sanitizes, t0a, elseB)),
        (taintWf(introduces, sanitizes, t0b, thenB) || taintWf(introduces, sanitizes, t0b, elseB)),
        rest);
  }
}

function taintWfSound(introduces: (int) -> bool, sanitizes: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf): bool
{
  true
}

lemma taintWfSound_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf)
  ensures (taintWfConcrete(introduces, sanitizes, chooseThen, t0, wf) ==> taintWf(introduces, sanitizes, t0, wf))
  decreases wf
{
  match wf {
    case done =>
    case tool(t, rest) =>
      taintWfSound_ensures(introduces, sanitizes, chooseThen,
        (if sanitizes(t) then false else (t0 || introduces(t))),
        rest);
    case cond(thenB, elseB, rest) =>
      taintWfSound_ensures(introduces, sanitizes, chooseThen, t0, thenB);
      taintWfSound_ensures(introduces, sanitizes, chooseThen, t0, elseB);
      var concBranched := (if chooseThen(wf) then taintWfConcrete(introduces, sanitizes, chooseThen, t0, thenB) else taintWfConcrete(introduces, sanitizes, chooseThen, t0, elseB));
      var absBranched := (taintWf(introduces, sanitizes, t0, thenB) || taintWf(introduces, sanitizes, t0, elseB));
      taintWfSound_ensures(introduces, sanitizes, chooseThen, concBranched, rest);
      taintWfMonotone_ensures(introduces, sanitizes, concBranched, absBranched, rest);
  }
}
