// Generated by lsc from wf_core.ts

datatype Wf = done | tool(tool: int, rest: Wf) | cond(thenB: Wf, elseB: Wf, rest: Wf)

function taintWf(introduces: (int) -> bool, sanitizes: (int) -> bool, t0: bool, wf: Wf): bool
  decreases wf
{
  match wf {
    case done =>
      t0
    case tool(i_wf_tool, i_wf_rest) =>
      var next := (if sanitizes(i_wf_tool) then false else (t0 || introduces(i_wf_tool)));
      taintWf(introduces, sanitizes, next, i_wf_rest)
    case cond(i_wf_thenB, i_wf_elseB, i_wf_rest) =>
      var branched := (taintWf(introduces, sanitizes, t0, i_wf_thenB) || taintWf(introduces, sanitizes, t0, i_wf_elseB));
      taintWf(introduces, sanitizes, branched, i_wf_rest)
  }
}

function taintWfConcrete(introduces: (int) -> bool, sanitizes: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf): bool
  decreases wf
{
  match wf {
    case done =>
      t0
    case tool(i_wf_tool, i_wf_rest) =>
      var next := (if sanitizes(i_wf_tool) then false else (t0 || introduces(i_wf_tool)));
      taintWfConcrete(introduces, sanitizes, chooseThen, next, i_wf_rest)
    case cond(i_wf_thenB, i_wf_elseB, i_wf_rest) =>
      var branched := (if chooseThen(wf) then taintWfConcrete(introduces, sanitizes, chooseThen, t0, i_wf_thenB) else taintWfConcrete(introduces, sanitizes, chooseThen, t0, i_wf_elseB));
      taintWfConcrete(introduces, sanitizes, chooseThen, branched, i_wf_rest)
  }
}

function taintWfMonotone(introduces: (int) -> bool, sanitizes: (int) -> bool, t0a: bool, t0b: bool, wf: Wf): bool
  requires (t0a ==> t0b)
{
  true
}

lemma taintWfMonotone_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, t0a: bool, t0b: bool, wf: Wf)
  requires (t0a ==> t0b)
  ensures (taintWf(introduces, sanitizes, t0a, wf) ==> taintWf(introduces, sanitizes, t0b, wf))
  decreases wf
{
  match wf {
    case done =>
    case tool(t, rest) =>
      taintWfMonotone_ensures(introduces, sanitizes,
        (if sanitizes(t) then false else (t0a || introduces(t))),
        (if sanitizes(t) then false else (t0b || introduces(t))),
        rest);
    case cond(thenB, elseB, rest) =>
      taintWfMonotone_ensures(introduces, sanitizes, t0a, t0b, thenB);
      taintWfMonotone_ensures(introduces, sanitizes, t0a, t0b, elseB);
      taintWfMonotone_ensures(introduces, sanitizes,
        (taintWf(introduces, sanitizes, t0a, thenB) || taintWf(introduces, sanitizes, t0a, elseB)),
        (taintWf(introduces, sanitizes, t0b, thenB) || taintWf(introduces, sanitizes, t0b, elseB)),
        rest);
  }
}

function taintWfSound(introduces: (int) -> bool, sanitizes: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf): bool
{
  true
}

lemma taintWfSound_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf)
  ensures (taintWfConcrete(introduces, sanitizes, chooseThen, t0, wf) ==> taintWf(introduces, sanitizes, t0, wf))
  decreases wf
{
  match wf {
    case done =>
    case tool(t, rest) =>
      taintWfSound_ensures(introduces, sanitizes, chooseThen,
        (if sanitizes(t) then false else (t0 || introduces(t))),
        rest);
    case cond(thenB, elseB, rest) =>
      taintWfSound_ensures(introduces, sanitizes, chooseThen, t0, thenB);
      taintWfSound_ensures(introduces, sanitizes, chooseThen, t0, elseB);
      var concBranched := (if chooseThen(wf) then taintWfConcrete(introduces, sanitizes, chooseThen, t0, thenB) else taintWfConcrete(introduces, sanitizes, chooseThen, t0, elseB));
      var absBranched := (taintWf(introduces, sanitizes, t0, thenB) || taintWf(introduces, sanitizes, t0, elseB));
      taintWfSound_ensures(introduces, sanitizes, chooseThen, concBranched, rest);
      taintWfMonotone_ensures(introduces, sanitizes, concBranched, absBranched, rest);
  }
}

function leaksWf(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, t0: bool, wf: Wf): bool
  decreases wf
{
  match wf {
    case done =>
      false
    case tool(i_wf_tool, i_wf_rest) =>
      var here := (isSink(i_wf_tool) && t0);
      var next := (if sanitizes(i_wf_tool) then false else (t0 || introduces(i_wf_tool)));
      (here || leaksWf(introduces, sanitizes, isSink, next, i_wf_rest))
    case cond(i_wf_thenB, i_wf_elseB, i_wf_rest) =>
      var branched := (taintWf(introduces, sanitizes, t0, i_wf_thenB) || taintWf(introduces, sanitizes, t0, i_wf_elseB));
      ((leaksWf(introduces, sanitizes, isSink, t0, i_wf_thenB) || leaksWf(introduces, sanitizes, isSink, t0, i_wf_elseB)) || leaksWf(introduces, sanitizes, isSink, branched, i_wf_rest))
  }
}

function leaksWfConcrete(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf): bool
  decreases wf
{
  match wf {
    case done =>
      false
    case tool(i_wf_tool, i_wf_rest) =>
      var here := (isSink(i_wf_tool) && t0);
      var next := (if sanitizes(i_wf_tool) then false else (t0 || introduces(i_wf_tool)));
      (here || leaksWfConcrete(introduces, sanitizes, isSink, chooseThen, next, i_wf_rest))
    case cond(i_wf_thenB, i_wf_elseB, i_wf_rest) =>
      var branchLeak := (if chooseThen(wf) then leaksWfConcrete(introduces, sanitizes, isSink, chooseThen, t0, i_wf_thenB) else leaksWfConcrete(introduces, sanitizes, isSink, chooseThen, t0, i_wf_elseB));
      var branched := (if chooseThen(wf) then taintWfConcrete(introduces, sanitizes, chooseThen, t0, i_wf_thenB) else taintWfConcrete(introduces, sanitizes, chooseThen, t0, i_wf_elseB));
      (branchLeak || leaksWfConcrete(introduces, sanitizes, isSink, chooseThen, branched, i_wf_rest))
  }
}

function leaksWfMonotone(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, t0a: bool, t0b: bool, wf: Wf): bool
  requires (t0a ==> t0b)
{
  true
}

lemma leaksWfMonotone_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, t0a: bool, t0b: bool, wf: Wf)
  requires (t0a ==> t0b)
  ensures (leaksWf(introduces, sanitizes, isSink, t0a, wf) ==> leaksWf(introduces, sanitizes, isSink, t0b, wf))
  decreases wf
{
  match wf {
    case done =>
    case tool(t, rest) =>
      leaksWfMonotone_ensures(introduces, sanitizes, isSink,
        (if sanitizes(t) then false else (t0a || introduces(t))),
        (if sanitizes(t) then false else (t0b || introduces(t))),
        rest);
    case cond(thenB, elseB, rest) =>
      leaksWfMonotone_ensures(introduces, sanitizes, isSink, t0a, t0b, thenB);
      leaksWfMonotone_ensures(introduces, sanitizes, isSink, t0a, t0b, elseB);
      taintWfMonotone_ensures(introduces, sanitizes, t0a, t0b, thenB);
      taintWfMonotone_ensures(introduces, sanitizes, t0a, t0b, elseB);
      leaksWfMonotone_ensures(introduces, sanitizes, isSink,
        (taintWf(introduces, sanitizes, t0a, thenB) || taintWf(introduces, sanitizes, t0a, elseB)),
        (taintWf(introduces, sanitizes, t0b, thenB) || taintWf(introduces, sanitizes, t0b, elseB)),
        rest);
  }
}

function leaksWfSound(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf): bool
{
  true
}

lemma leaksWfSound_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf)
  ensures (leaksWfConcrete(introduces, sanitizes, isSink, chooseThen, t0, wf) ==> leaksWf(introduces, sanitizes, isSink, t0, wf))
  decreases wf
{
  match wf {
    case done =>
    case tool(t, rest) =>
      leaksWfSound_ensures(introduces, sanitizes, isSink, chooseThen,
        (if sanitizes(t) then false else (t0 || introduces(t))),
        rest);
    case cond(thenB, elseB, rest) =>
      leaksWfSound_ensures(introduces, sanitizes, isSink, chooseThen, t0, thenB);
      leaksWfSound_ensures(introduces, sanitizes, isSink, chooseThen, t0, elseB);
      taintWfSound_ensures(introduces, sanitizes, chooseThen, t0, thenB);
      taintWfSound_ensures(introduces, sanitizes, chooseThen, t0, elseB);
      var concBranched := (if chooseThen(wf) then taintWfConcrete(introduces, sanitizes, chooseThen, t0, thenB) else taintWfConcrete(introduces, sanitizes, chooseThen, t0, elseB));
      var absBranched := (taintWf(introduces, sanitizes, t0, thenB) || taintWf(introduces, sanitizes, t0, elseB));
      leaksWfSound_ensures(introduces, sanitizes, isSink, chooseThen, concBranched, rest);
      leaksWfMonotone_ensures(introduces, sanitizes, isSink, concBranched, absBranched, rest);
  }
}

function reachesTargetWf(isTarget: (int) -> bool, wf: Wf): bool
  decreases wf
{
  match wf {
    case done =>
      false
    case tool(i_wf_tool, i_wf_rest) =>
      (isTarget(i_wf_tool) || reachesTargetWf(isTarget, i_wf_rest))
    case cond(i_wf_thenB, i_wf_elseB, i_wf_rest) =>
      ((reachesTargetWf(isTarget, i_wf_thenB) || reachesTargetWf(isTarget, i_wf_elseB)) || reachesTargetWf(isTarget, i_wf_rest))
  }
}

function reachesTargetWfConcrete(isTarget: (int) -> bool, chooseThen: (Wf) -> bool, wf: Wf): bool
  decreases wf
{
  match wf {
    case done =>
      false
    case tool(i_wf_tool, i_wf_rest) =>
      (isTarget(i_wf_tool) || reachesTargetWfConcrete(isTarget, chooseThen, i_wf_rest))
    case cond(i_wf_thenB, i_wf_elseB, i_wf_rest) =>
      var branch := (if chooseThen(wf) then reachesTargetWfConcrete(isTarget, chooseThen, i_wf_thenB) else reachesTargetWfConcrete(isTarget, chooseThen, i_wf_elseB));
      (branch || reachesTargetWfConcrete(isTarget, chooseThen, i_wf_rest))
  }
}

function reachesTargetWfSound(isTarget: (int) -> bool, chooseThen: (Wf) -> bool, wf: Wf): bool
{
  true
}

lemma reachesTargetWfSound_ensures(isTarget: (int) -> bool, chooseThen: (Wf) -> bool, wf: Wf)
  ensures (reachesTargetWfConcrete(isTarget, chooseThen, wf) ==> reachesTargetWf(isTarget, wf))
  decreases wf
{
  match wf {
    case done =>
    case tool(t, rest) =>
      reachesTargetWfSound_ensures(isTarget, chooseThen, rest);
    case cond(thenB, elseB, rest) =>
      reachesTargetWfSound_ensures(isTarget, chooseThen, thenB);
      reachesTargetWfSound_ensures(isTarget, chooseThen, elseB);
      reachesTargetWfSound_ensures(isTarget, chooseThen, rest);
  }
}

function verifyWf(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, isTarget: (int) -> bool, t0: bool, wf: Wf): bool
{
  (!(leaksWf(introduces, sanitizes, isSink, t0, wf)) && !(reachesTargetWf(isTarget, wf)))
}

function verifyWfSound(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, isTarget: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf): bool
{
  true
}

lemma verifyWfSound_ensures(introduces: (int) -> bool, sanitizes: (int) -> bool, isSink: (int) -> bool, isTarget: (int) -> bool, chooseThen: (Wf) -> bool, t0: bool, wf: Wf)
  ensures (verifyWf(introduces, sanitizes, isSink, isTarget, t0, wf) ==> (!(leaksWfConcrete(introduces, sanitizes, isSink, chooseThen, t0, wf)) && !(reachesTargetWfConcrete(isTarget, chooseThen, wf))))
{
  leaksWfSound_ensures(introduces, sanitizes, isSink, chooseThen, t0, wf);
  reachesTargetWfSound_ensures(isTarget, chooseThen, wf);
}
